spring:
  profiles:
    active: mongo
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true
logging:
  level:
    study.ronoyaro: debug
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20